export default [
  {
    name: "Harry",
    lastName: "Potter",
    age: 16,
    adult: false,
    level: 7,
    house: "Gryffindor",
    credits: 7,
  },
  {
    name: "Ron",
    lastName: "Weasly",
    age: 17,
    adult: false,
    level: 6,
    house: "Gryffindor",
    credits: 6,
  },
  {
    name: "Hermione",
    lastName: "Granger",
    age: 16,
    adult: false,
    level: 9,
    house: "Gryffindor",
    credits: 10,
  },
  {
    name: "Draco",
    lastName: "Malfoy",
    age: 15,
    adult: false,
    level: 7,
    house: "Slytherin",
    credits: 8,
  },
  {
    name: "Vincent",
    lastName: "Crabb",
    age: 17,
    adult: false,
    level: 5,
    house: "Slytherin",
    credits: 5,
  },
  {
    name: "Gregory",
    lastName: "Goyle",
    age: 17,
    adult: false,
    level: 5,
    house: "Slytherin",
    credits: 5,
  },
  {
    name: "Cedric",
    lastName: "Diggory",
    age: 18,
    adult: true,
    level: 9,
    house: "Hufflepuff",
    credits: 10,
  },
  {
    name: "Ernie",
    lastName: "Macmillan",
    age: 17,
    adult: false,
    level: 6,
    house: "Hufflepuff",
    credits: 7,
  },
  {
    name: "Hannah",
    lastName: "Abbot",
    age: 16,
    adult: false,
    level: 6,
    house: "Hufflepuff",
    credits: 6,
  },
  {
    name: "Luna",
    lastName: "Lovegood",
    age: 15,
    adult: false,
    level: 7,
    house: "Ravenclaw",
    credits: 6,
  },
  {
    name: "Cho",
    lastName: "Chhang",
    age: 15,
    adult: false,
    level: 6,
    house: "Ravenclaw",
    credits: 7,
  },
  {
    name: "Terry",
    lastName: "Boot",
    age: 18,
    adult: true,
    level: 5,
    house: "Ravenclaw",
    credits: 6,
  },
];
